move files before import

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -23,6 +23,12 @@ export BUILDPACK_PATH=$BP_DIR
 source $BP_DIR/compile-extensions/lib/common
 # END CF Common
 
+### Load base app files
+
+cp -R $BP_DIR/base_app/ $BUILD_DIR
+ls -lsa $BP_DIR/base_app/
+ls -lsa $BUILD_DIR/base_app/
+
 ### Load dependencies
 
 source $BP_DIR/lib/output.sh
@@ -33,119 +39,113 @@ source $BP_DIR/lib/binaries.sh
 source $BP_DIR/lib/cache.sh
 source $BP_DIR/lib/dependencies.sh
 
-### Load base app files
+### Handle errors
 
-cp -R $BP_DIR/base_app/ $BUILD_DIR
-ls -lsa $BP_DIR/base_app/
-ls -lsa $BUILD_DIR/base_app/
+handle_failure() {
+  header "Build failed"
+  failure_message | indent
+}
+trap 'handle_failure' ERR
 
-# ### Handle errors
+### Ship with a sandbox of modules already set up
 
-# handle_failure() {
-#   header "Build failed"
-#   failure_message | indent
-# }
-# trap 'handle_failure' ERR
+PREBUILD=true
 
-# ### Ship with a sandbox of modules already set up
+### Failures that should be caught immediately
 
-# PREBUILD=true
+fail_invalid_package_json "$BUILD_DIR"
+warn_prebuilt_modules "$BUILD_DIR"
+warn_missing_package_json "$BUILD_DIR"
 
-# ### Failures that should be caught immediately
+### Compile
 
-# fail_invalid_package_json "$BUILD_DIR"
-# warn_prebuilt_modules "$BUILD_DIR"
-# warn_missing_package_json "$BUILD_DIR"
+create_env() {
+  write_profile "$BP_DIR" "$BUILD_DIR"
+  export_env_dir "$ENV_DIR"
+  create_default_env
+}
 
-# ### Compile
+header "Creating runtime environment"
+create_env # can't indent the whole thing because piping causes subshells; no exporting possible
+list_node_config | indent
 
-# create_env() {
-#   write_profile "$BP_DIR" "$BUILD_DIR"
-#   export_env_dir "$ENV_DIR"
-#   create_default_env
-# }
+install_bins() {
+  local node_engine=$(read_json "$BUILD_DIR/package.json" ".engines.node")
+  local iojs_engine=$(read_json "$BUILD_DIR/package.json" ".engines.iojs")
+  local npm_engine=$(read_json "$BUILD_DIR/package.json" ".engines.npm")
 
-# header "Creating runtime environment"
-# create_env # can't indent the whole thing because piping causes subshells; no exporting possible
-# list_node_config | indent
+  if [ -n "$iojs_engine" ]; then
+    echo "engines.iojs (package.json):  $iojs_engine (iojs)"
+  else
+    echo "engines.node (package.json):  ${node_engine:-unspecified}"
+  fi
+  echo "engines.npm (package.json):   ${npm_engine:-unspecified (use default)}"
+  echo ""
 
-# install_bins() {
-#   local node_engine=$(read_json "$BUILD_DIR/package.json" ".engines.node")
-#   local iojs_engine=$(read_json "$BUILD_DIR/package.json" ".engines.iojs")
-#   local npm_engine=$(read_json "$BUILD_DIR/package.json" ".engines.npm")
+  if [ -n "$iojs_engine" ]; then
+    warn_node_engine "$iojs_engine"
+    install_iojs "$iojs_engine" "$BUILD_DIR/.heroku/node"
+  else
+    warn_node_engine "$node_engine"
+    install_nodejs "$node_engine" "$BUILD_DIR/.heroku/node"
+  fi
+  install_npm "$npm_engine" "$BUILD_DIR/.heroku/node"
+  warn_old_npm
+}
 
-#   if [ -n "$iojs_engine" ]; then
-#     echo "engines.iojs (package.json):  $iojs_engine (iojs)"
-#   else
-#     echo "engines.node (package.json):  ${node_engine:-unspecified}"
-#   fi
-#   echo "engines.npm (package.json):   ${npm_engine:-unspecified (use default)}"
-#   echo ""
+header "Installing binaries"
+install_bins | indent
 
-#   if [ -n "$iojs_engine" ]; then
-#     warn_node_engine "$iojs_engine"
-#     install_iojs "$iojs_engine" "$BUILD_DIR/.heroku/node"
-#   else
-#     warn_node_engine "$node_engine"
-#     install_nodejs "$node_engine" "$BUILD_DIR/.heroku/node"
-#   fi
-#   install_npm "$npm_engine" "$BUILD_DIR/.heroku/node"
-#   warn_old_npm
-# }
+restore_cache() {
+  local cache_status=$(get_cache_status)
 
-# header "Installing binaries"
-# install_bins | indent
+  if [ "$cache_status" == "disabled" ]; then
+    echo "Skipping (cache disabled)"
+  elif [ "$cache_status" == "invalidated" ]; then
+    echo "Skipping (cache invalidated)"
+  else
+    local cache_directories=$(get_cache_directories)
+    if [ "$cache_directories" == "" ]; then
+      echo "Loading 1 from cacheDirectories (default):"
+      restore_cache_directories "$BUILD_DIR" "$CACHE_DIR" "node_modules"
+    else
+      echo "Loading $(echo $cache_directories | wc -w | xargs) from cacheDirectories (package.json):"
+      restore_cache_directories "$BUILD_DIR" "$CACHE_DIR" $cache_directories
+    fi
+  fi
+}
 
-# restore_cache() {
-#   local cache_status=$(get_cache_status)
+header "Restoring cache"
+restore_cache | indent
 
-#   if [ "$cache_status" == "disabled" ]; then
-#     echo "Skipping (cache disabled)"
-#   elif [ "$cache_status" == "invalidated" ]; then
-#     echo "Skipping (cache invalidated)"
-#   else
-#     local cache_directories=$(get_cache_directories)
-#     if [ "$cache_directories" == "" ]; then
-#       echo "Loading 1 from cacheDirectories (default):"
-#       restore_cache_directories "$BUILD_DIR" "$CACHE_DIR" "node_modules"
-#     else
-#       echo "Loading $(echo $cache_directories | wc -w | xargs) from cacheDirectories (package.json):"
-#       restore_cache_directories "$BUILD_DIR" "$CACHE_DIR" $cache_directories
-#     fi
-#   fi
-# }
+build_dependencies() {
+  echo "Rebuilding node modules"
+  rebuild_node_modules "$BUILD_DIR"
+}
 
-# header "Restoring cache"
-# restore_cache | indent
+header "Building dependencies"
+build_dependencies | indent
 
-# build_dependencies() {
-#   echo "Rebuilding node modules"
-#   rebuild_node_modules "$BUILD_DIR"
-# }
+cache_build() {
+  local cache_directories=$(get_cache_directories)
+  echo "Clearing previous node cache"
+  clear_cache
+  if [ "$cache_directories" == "" ]; then
+    echo "Saving 1 cacheDirectories (default):"
+    save_cache_directories "$BUILD_DIR" "$CACHE_DIR" "node_modules"
+  else
+    echo "Saving $(echo $cache_directories | wc -w | xargs) cacheDirectories (package.json):"
+    save_cache_directories "$BUILD_DIR" "$CACHE_DIR" $cache_directories
+  fi
+}
 
-# header "Building dependencies"
-# build_dependencies | indent
+header "Caching build"
+cache_build | indent
 
-# cache_build() {
-#   local cache_directories=$(get_cache_directories)
-#   echo "Clearing previous node cache"
-#   clear_cache
-#   if [ "$cache_directories" == "" ]; then
-#     echo "Saving 1 cacheDirectories (default):"
-#     save_cache_directories "$BUILD_DIR" "$CACHE_DIR" "node_modules"
-#   else
-#     echo "Saving $(echo $cache_directories | wc -w | xargs) cacheDirectories (package.json):"
-#     save_cache_directories "$BUILD_DIR" "$CACHE_DIR" $cache_directories
-#   fi
-# }
+summarize_build() {
+  cd $BUILD_DIR
+  (npm ls --depth=0 | tail -n +2 || true) 2>/dev/null
+}
 
-# header "Caching build"
-# cache_build | indent
-
-# summarize_build() {
-#   cd $BUILD_DIR
-#   (npm ls --depth=0 | tail -n +2 || true) 2>/dev/null
-# }
-
-# header "Build succeeded!"
-# summarize_build | indent
+header "Build succeeded!"
+summarize_build | indent
